version: '3'

services:
  chatservice:
    build: .
    container_name: chatservice_app
    volumes:
      - .:/go/src
    ports:
      - "8081:8080"
      - "50052:50051"

  # mysql:
  #   image: mysql:latest
  #   container_name: mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: chat_test
  #     MYSQL_PASSWORD: root
  #   expose:
  #     - "3306"
  #   ports:
  #     - 3306:3306  
  #   volumes:
  #     - "./docker_data/mysql:/var/lib/mysql"
  postgres:
    build:
      context: .
      dockerfile: postgres.dockerfile
    image: "postgres:latest"
    container_name: ${CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: ${DB_DATA}
    volumes:
       - dbchat:${DB_DATA}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: unless-stopped
volumes:
    dbchat:
      external: true

  # postgres:
  #   image: postgres:latest
  #   container_name: postgres
  #   # volumes:
  #   #   - ./postgres_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_PASSWORD=root
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=${DB_NAME}
  #   ports:
  #     - 5432:5432